# Generated by Django 4.1 on 2022-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("start_date", models.CharField(max_length=100)),
                ("end_date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Familiarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("description_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=50)),
                ("about_me", models.TextField()),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=50)),
                ("profile_image", models.ImageField(upload_to="profile")),
                ("phone", models.CharField(max_length=11)),
                ("linkedin", models.CharField(max_length=100)),
                ("github", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copyright_text", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("description_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
