# Generated by Django 4.1 on 2022-09-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_worked"),
    ]

    operations = [
        migrations.RenameModel(old_name="Worked", new_name="Experience",),
    ]
