# Generated by Django 4.1 on 2022-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_rename_worked_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="github",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="linkedin",
            field=models.CharField(max_length=100),
        ),
    ]
